name: demo
run-name: demo
on:
  push:
    branches:
      - main
jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload dockerfile
        uses: actions/upload-artifact@v2
        with:
          name: dockerfile
          path: Dockerfile
  cat:
    runs-on: ubuntu-latest
    needs: hi
    steps:
      - name: Download dockerfile
        uses: actions/download-artifact@v2
        with:
          name: dockerfile
